### ISSUE TITLE
Document our standard github workflows

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/open-source-guide#8]
Create a new "Workflows" folder with the following sub-folders:

- Oversight - Move [this section](https://github.com/RhoInc/open-source-handbook#step-by-step-guide-for-open-source-projects-at-rho) there
- Releases - Outline the process for planning/implementing a new release 
- Issues - Outline the process for making a single change.

Each subfolder gets a README.md

**Comment by brittsikora** [comment]
I've reviewed your work, added more documentation from our OSC meetings, and passed it along to Ryan for QC - can we close this?

**Comment by rtbailey** [comment]
I see @brittsikora additions to the FAQ and they look good.  I couldn't find the "Workflows" folder.  @jwildfire probably has to comment on whether or not we can close as I'm not sure whether the original task, as worded above, has been addressed, or whether there's something else that needs to be done.

**Comment by brittsikora** [comment]
I just got the go-ahead to close the issue and release
